/*
 * Работа с товарами
 *
 * Работа с товарами включает в себя:   1. [Создание](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактирование](/openapi/work-with-products#tag/Kartochki-tovarov) карточек товаров: в том числе, получение [категорий, предметов и характеристик товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki) и загрузку [медиафайлов](/openapi/work-with-products#tag/Mediafajly).   2. Настройку [ярлыков](/openapi/work-with-products#tag/Yarlyki) для удобного поиска товаров.   3. Установку [цен и скидок](/openapi/work-with-products#tag/Ceny-i-skidki).   4. Управление [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца. 
 *
 * The version of the OpenAPI document: products
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ApiV2HistoryGoodsTaskGet200ResponseData
    /// </summary>
    [DataContract(Name = "_api_v2_history_goods_task_get_200_response_data")]
    public partial class ApiV2HistoryGoodsTaskGet200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiV2HistoryGoodsTaskGet200ResponseData" /> class.
        /// </summary>
        /// <param name="uploadID">ID загрузки.</param>
        /// <param name="historyGoods">Информация о товарах в загрузке.</param>
        public ApiV2HistoryGoodsTaskGet200ResponseData(int uploadID = default(int), List<GoodHistory> historyGoods = default(List<GoodHistory>))
        {
            this.UploadID = uploadID;
            this.HistoryGoods = historyGoods;
        }

        /// <summary>
        /// ID загрузки
        /// </summary>
        /// <value>ID загрузки</value>
        /*
        <example>3235236546</example>
        */
        [DataMember(Name = "uploadID", EmitDefaultValue = false)]
        public int UploadID { get; set; }

        /// <summary>
        /// Информация о товарах в загрузке
        /// </summary>
        /// <value>Информация о товарах в загрузке</value>
        [DataMember(Name = "historyGoods", EmitDefaultValue = false)]
        public List<GoodHistory> HistoryGoods { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApiV2HistoryGoodsTaskGet200ResponseData {\n");
            sb.Append("  UploadID: ").Append(UploadID).Append("\n");
            sb.Append("  HistoryGoods: ").Append(HistoryGoods).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
