/*
 * Работа с товарами
 *
 * Работа с товарами включает в себя:   1. [Создание](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактирование](/openapi/work-with-products#tag/Kartochki-tovarov) карточек товаров: в том числе, получение [категорий, предметов и характеристик товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki) и загрузку [медиафайлов](/openapi/work-with-products#tag/Mediafajly).   2. Настройку [ярлыков](/openapi/work-with-products#tag/Yarlyki) для удобного поиска товаров.   3. Установку [цен и скидок](/openapi/work-with-products#tag/Ceny-i-skidki).   4. Управление [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца. 
 *
 * The version of the OpenAPI document: products
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ContentV2ObjectAllGet200ResponseDataInner
    /// </summary>
    [DataContract(Name = "_content_v2_object_all_get_200_response_data_inner")]
    public partial class ContentV2ObjectAllGet200ResponseDataInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ContentV2ObjectAllGet200ResponseDataInner" /> class.
        /// </summary>
        /// <param name="subjectID">ID предмета.</param>
        /// <param name="parentID">ID родительской категории.</param>
        /// <param name="subjectName">Название предмета.</param>
        /// <param name="parentName">Название родительской категории.</param>
        public ContentV2ObjectAllGet200ResponseDataInner(int subjectID = default(int), int parentID = default(int), string subjectName = default(string), string parentName = default(string))
        {
            this.SubjectID = subjectID;
            this.ParentID = parentID;
            this.SubjectName = subjectName;
            this.ParentName = parentName;
        }

        /// <summary>
        /// ID предмета
        /// </summary>
        /// <value>ID предмета</value>
        [DataMember(Name = "subjectID", EmitDefaultValue = false)]
        public int SubjectID { get; set; }

        /// <summary>
        /// ID родительской категории
        /// </summary>
        /// <value>ID родительской категории</value>
        [DataMember(Name = "parentID", EmitDefaultValue = false)]
        public int ParentID { get; set; }

        /// <summary>
        /// Название предмета
        /// </summary>
        /// <value>Название предмета</value>
        [DataMember(Name = "subjectName", EmitDefaultValue = false)]
        public string SubjectName { get; set; }

        /// <summary>
        /// Название родительской категории
        /// </summary>
        /// <value>Название родительской категории</value>
        [DataMember(Name = "parentName", EmitDefaultValue = false)]
        public string ParentName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ContentV2ObjectAllGet200ResponseDataInner {\n");
            sb.Append("  SubjectID: ").Append(SubjectID).Append("\n");
            sb.Append("  ParentID: ").Append(ParentID).Append("\n");
            sb.Append("  SubjectName: ").Append(SubjectName).Append("\n");
            sb.Append("  ParentName: ").Append(ParentName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
