/*
 * Работа с товарами
 *
 * Работа с товарами включает в себя:   1. [Создание](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактирование](/openapi/work-with-products#tag/Kartochki-tovarov) карточек товаров: в том числе, получение [категорий, предметов и характеристик товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki) и загрузку [медиафайлов](/openapi/work-with-products#tag/Mediafajly).   2. Настройку [ярлыков](/openapi/work-with-products#tag/Yarlyki) для удобного поиска товаров.   3. Установку [цен и скидок](/openapi/work-with-products#tag/Ceny-i-skidki).   4. Управление [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца. 
 *
 * The version of the OpenAPI document: products
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ContentV2CardsUploadPostRequestInner
    /// </summary>
    [DataContract(Name = "_content_v2_cards_upload_post_request_inner")]
    public partial class ContentV2CardsUploadPostRequestInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ContentV2CardsUploadPostRequestInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ContentV2CardsUploadPostRequestInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ContentV2CardsUploadPostRequestInner" /> class.
        /// </summary>
        /// <param name="subjectID">ID предмета (required).</param>
        /// <param name="variants">Массив вариантов товара. В каждой карточке товара может быть не более 30 карточек товаров (required).</param>
        public ContentV2CardsUploadPostRequestInner(int subjectID = default(int), List<ContentV2CardsUploadPostRequestInnerVariantsInner> variants = default(List<ContentV2CardsUploadPostRequestInnerVariantsInner>))
        {
            this.SubjectID = subjectID;
            // to ensure "variants" is required (not null)
            if (variants == null)
            {
                throw new ArgumentNullException("variants is a required property for ContentV2CardsUploadPostRequestInner and cannot be null");
            }
            this.Variants = variants;
        }

        /// <summary>
        /// ID предмета
        /// </summary>
        /// <value>ID предмета</value>
        [DataMember(Name = "subjectID", IsRequired = true, EmitDefaultValue = true)]
        public int SubjectID { get; set; }

        /// <summary>
        /// Массив вариантов товара. В каждой карточке товара может быть не более 30 карточек товаров
        /// </summary>
        /// <value>Массив вариантов товара. В каждой карточке товара может быть не более 30 карточек товаров</value>
        [DataMember(Name = "variants", IsRequired = true, EmitDefaultValue = true)]
        public List<ContentV2CardsUploadPostRequestInnerVariantsInner> Variants { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ContentV2CardsUploadPostRequestInner {\n");
            sb.Append("  SubjectID: ").Append(SubjectID).Append("\n");
            sb.Append("  Variants: ").Append(Variants).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
