/*
 * Работа с товарами
 *
 * Работа с товарами включает в себя:   1. [Создание](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактирование](/openapi/work-with-products#tag/Kartochki-tovarov) карточек товаров: в том числе, получение [категорий, предметов и характеристик товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki) и загрузку [медиафайлов](/openapi/work-with-products#tag/Mediafajly).   2. Настройку [ярлыков](/openapi/work-with-products#tag/Yarlyki) для удобного поиска товаров.   3. Установку [цен и скидок](/openapi/work-with-products#tag/Ceny-i-skidki).   4. Управление [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца. 
 *
 * The version of the OpenAPI document: products
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Размеры товара
    /// </summary>
    [DataContract(Name = "GoodsList")]
    public partial class GoodsList : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GoodsList" /> class.
        /// </summary>
        /// <param name="nmID">Артикул WB.</param>
        /// <param name="vendorCode">Артикул продавца.</param>
        /// <param name="sizes">Размер.</param>
        /// <param name="currencyIsoCode4217">Валюта, по стандарту ISO 4217.</param>
        /// <param name="discount">Скидка, %.</param>
        /// <param name="clubDiscount">Скидка WB Клуба, %.</param>
        /// <param name="editableSizePrice">Можно ли устанавливать цены отдельно для разных размеров: &#x60;true&#x60; — можно, &#x60;false&#x60; — нельзя. Эта возможность зависит от категории товара .</param>
        public GoodsList(int nmID = default(int), string vendorCode = default(string), List<GoodsListSizesInner> sizes = default(List<GoodsListSizesInner>), string currencyIsoCode4217 = default(string), int discount = default(int), int clubDiscount = default(int), bool editableSizePrice = default(bool))
        {
            this.NmID = nmID;
            this.VendorCode = vendorCode;
            this.Sizes = sizes;
            this.CurrencyIsoCode4217 = currencyIsoCode4217;
            this.Discount = discount;
            this.ClubDiscount = clubDiscount;
            this.EditableSizePrice = editableSizePrice;
        }

        /// <summary>
        /// Артикул WB
        /// </summary>
        /// <value>Артикул WB</value>
        /*
        <example>98486</example>
        */
        [DataMember(Name = "nmID", EmitDefaultValue = false)]
        public int NmID { get; set; }

        /// <summary>
        /// Артикул продавца
        /// </summary>
        /// <value>Артикул продавца</value>
        /*
        <example>07326060</example>
        */
        [DataMember(Name = "vendorCode", EmitDefaultValue = false)]
        public string VendorCode { get; set; }

        /// <summary>
        /// Размер
        /// </summary>
        /// <value>Размер</value>
        [DataMember(Name = "sizes", EmitDefaultValue = false)]
        public List<GoodsListSizesInner> Sizes { get; set; }

        /// <summary>
        /// Валюта, по стандарту ISO 4217
        /// </summary>
        /// <value>Валюта, по стандарту ISO 4217</value>
        /*
        <example>RUB</example>
        */
        [DataMember(Name = "currencyIsoCode4217", EmitDefaultValue = false)]
        public string CurrencyIsoCode4217 { get; set; }

        /// <summary>
        /// Скидка, %
        /// </summary>
        /// <value>Скидка, %</value>
        /*
        <example>30</example>
        */
        [DataMember(Name = "discount", EmitDefaultValue = false)]
        public int Discount { get; set; }

        /// <summary>
        /// Скидка WB Клуба, %
        /// </summary>
        /// <value>Скидка WB Клуба, %</value>
        /*
        <example>5</example>
        */
        [DataMember(Name = "clubDiscount", EmitDefaultValue = false)]
        public int ClubDiscount { get; set; }

        /// <summary>
        /// Можно ли устанавливать цены отдельно для разных размеров: &#x60;true&#x60; — можно, &#x60;false&#x60; — нельзя. Эта возможность зависит от категории товара 
        /// </summary>
        /// <value>Можно ли устанавливать цены отдельно для разных размеров: &#x60;true&#x60; — можно, &#x60;false&#x60; — нельзя. Эта возможность зависит от категории товара </value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "editableSizePrice", EmitDefaultValue = true)]
        public bool EditableSizePrice { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GoodsList {\n");
            sb.Append("  NmID: ").Append(NmID).Append("\n");
            sb.Append("  VendorCode: ").Append(VendorCode).Append("\n");
            sb.Append("  Sizes: ").Append(Sizes).Append("\n");
            sb.Append("  CurrencyIsoCode4217: ").Append(CurrencyIsoCode4217).Append("\n");
            sb.Append("  Discount: ").Append(Discount).Append("\n");
            sb.Append("  ClubDiscount: ").Append(ClubDiscount).Append("\n");
            sb.Append("  EditableSizePrice: ").Append(EditableSizePrice).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
