/*
 * Работа с товарами
 *
 * Работа с товарами включает в себя:   1. [Создание](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактирование](/openapi/work-with-products#tag/Kartochki-tovarov) карточек товаров: в том числе, получение [категорий, предметов и характеристик товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki) и загрузку [медиафайлов](/openapi/work-with-products#tag/Mediafajly).   2. Настройку [ярлыков](/openapi/work-with-products#tag/Yarlyki) для удобного поиска товаров.   3. Установку [цен и скидок](/openapi/work-with-products#tag/Ceny-i-skidki).   4. Управление [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца. 
 *
 * The version of the OpenAPI document: products
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ContentV2GetCardsListPostRequestSettingsFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContentV2GetCardsListPostRequestSettingsFilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ContentV2GetCardsListPostRequestSettingsFilter
        //private ContentV2GetCardsListPostRequestSettingsFilter instance;

        public ContentV2GetCardsListPostRequestSettingsFilterTests()
        {
            // TODO uncomment below to create an instance of ContentV2GetCardsListPostRequestSettingsFilter
            //instance = new ContentV2GetCardsListPostRequestSettingsFilter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ContentV2GetCardsListPostRequestSettingsFilter
        /// </summary>
        [Fact]
        public void ContentV2GetCardsListPostRequestSettingsFilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" ContentV2GetCardsListPostRequestSettingsFilter
            //Assert.IsType<ContentV2GetCardsListPostRequestSettingsFilter>(instance);
        }

        /// <summary>
        /// Test the property 'WithPhoto'
        /// </summary>
        [Fact]
        public void WithPhotoTest()
        {
            // TODO unit test for the property 'WithPhoto'
        }

        /// <summary>
        /// Test the property 'TextSearch'
        /// </summary>
        [Fact]
        public void TextSearchTest()
        {
            // TODO unit test for the property 'TextSearch'
        }

        /// <summary>
        /// Test the property 'TagIDs'
        /// </summary>
        [Fact]
        public void TagIDsTest()
        {
            // TODO unit test for the property 'TagIDs'
        }

        /// <summary>
        /// Test the property 'AllowedCategoriesOnly'
        /// </summary>
        [Fact]
        public void AllowedCategoriesOnlyTest()
        {
            // TODO unit test for the property 'AllowedCategoriesOnly'
        }

        /// <summary>
        /// Test the property 'ObjectIDs'
        /// </summary>
        [Fact]
        public void ObjectIDsTest()
        {
            // TODO unit test for the property 'ObjectIDs'
        }

        /// <summary>
        /// Test the property 'Brands'
        /// </summary>
        [Fact]
        public void BrandsTest()
        {
            // TODO unit test for the property 'Brands'
        }

        /// <summary>
        /// Test the property 'ImtID'
        /// </summary>
        [Fact]
        public void ImtIDTest()
        {
            // TODO unit test for the property 'ImtID'
        }
    }
}
