/*
 * Работа с товарами
 *
 * Работа с товарами включает в себя:   1. [Создание](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактирование](/openapi/work-with-products#tag/Kartochki-tovarov) карточек товаров: в том числе, получение [категорий, предметов и характеристик товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki) и загрузку [медиафайлов](/openapi/work-with-products#tag/Mediafajly).   2. Настройку [ярлыков](/openapi/work-with-products#tag/Yarlyki) для удобного поиска товаров.   3. Установку [цен и скидок](/openapi/work-with-products#tag/Ceny-i-skidki).   4. Управление [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца. 
 *
 * The version of the OpenAPI document: products
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ContentV2GetCardsListPost200ResponseCardsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContentV2GetCardsListPost200ResponseCardsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ContentV2GetCardsListPost200ResponseCardsInner
        //private ContentV2GetCardsListPost200ResponseCardsInner instance;

        public ContentV2GetCardsListPost200ResponseCardsInnerTests()
        {
            // TODO uncomment below to create an instance of ContentV2GetCardsListPost200ResponseCardsInner
            //instance = new ContentV2GetCardsListPost200ResponseCardsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ContentV2GetCardsListPost200ResponseCardsInner
        /// </summary>
        [Fact]
        public void ContentV2GetCardsListPost200ResponseCardsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" ContentV2GetCardsListPost200ResponseCardsInner
            //Assert.IsType<ContentV2GetCardsListPost200ResponseCardsInner>(instance);
        }

        /// <summary>
        /// Test the property 'NmID'
        /// </summary>
        [Fact]
        public void NmIDTest()
        {
            // TODO unit test for the property 'NmID'
        }

        /// <summary>
        /// Test the property 'ImtID'
        /// </summary>
        [Fact]
        public void ImtIDTest()
        {
            // TODO unit test for the property 'ImtID'
        }

        /// <summary>
        /// Test the property 'NmUUID'
        /// </summary>
        [Fact]
        public void NmUUIDTest()
        {
            // TODO unit test for the property 'NmUUID'
        }

        /// <summary>
        /// Test the property 'SubjectID'
        /// </summary>
        [Fact]
        public void SubjectIDTest()
        {
            // TODO unit test for the property 'SubjectID'
        }

        /// <summary>
        /// Test the property 'VendorCode'
        /// </summary>
        [Fact]
        public void VendorCodeTest()
        {
            // TODO unit test for the property 'VendorCode'
        }

        /// <summary>
        /// Test the property 'SubjectName'
        /// </summary>
        [Fact]
        public void SubjectNameTest()
        {
            // TODO unit test for the property 'SubjectName'
        }

        /// <summary>
        /// Test the property 'Brand'
        /// </summary>
        [Fact]
        public void BrandTest()
        {
            // TODO unit test for the property 'Brand'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Photos'
        /// </summary>
        [Fact]
        public void PhotosTest()
        {
            // TODO unit test for the property 'Photos'
        }

        /// <summary>
        /// Test the property 'Video'
        /// </summary>
        [Fact]
        public void VideoTest()
        {
            // TODO unit test for the property 'Video'
        }

        /// <summary>
        /// Test the property 'Dimensions'
        /// </summary>
        [Fact]
        public void DimensionsTest()
        {
            // TODO unit test for the property 'Dimensions'
        }

        /// <summary>
        /// Test the property 'Characteristics'
        /// </summary>
        [Fact]
        public void CharacteristicsTest()
        {
            // TODO unit test for the property 'Characteristics'
        }

        /// <summary>
        /// Test the property 'Sizes'
        /// </summary>
        [Fact]
        public void SizesTest()
        {
            // TODO unit test for the property 'Sizes'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
