/*
 * Работа с товарами
 *
 * Работа с товарами включает в себя:   1. [Создание](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактирование](/openapi/work-with-products#tag/Kartochki-tovarov) карточек товаров: в том числе, получение [категорий, предметов и характеристик товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki) и загрузку [медиафайлов](/openapi/work-with-products#tag/Mediafajly).   2. Настройку [ярлыков](/openapi/work-with-products#tag/Yarlyki) для удобного поиска товаров.   3. Установку [цен и скидок](/openapi/work-with-products#tag/Ceny-i-skidki).   4. Управление [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца. 
 *
 * The version of the OpenAPI document: products
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ContentV2CardsUploadPostRequestInnerVariantsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContentV2CardsUploadPostRequestInnerVariantsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ContentV2CardsUploadPostRequestInnerVariantsInner
        //private ContentV2CardsUploadPostRequestInnerVariantsInner instance;

        public ContentV2CardsUploadPostRequestInnerVariantsInnerTests()
        {
            // TODO uncomment below to create an instance of ContentV2CardsUploadPostRequestInnerVariantsInner
            //instance = new ContentV2CardsUploadPostRequestInnerVariantsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ContentV2CardsUploadPostRequestInnerVariantsInner
        /// </summary>
        [Fact]
        public void ContentV2CardsUploadPostRequestInnerVariantsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" ContentV2CardsUploadPostRequestInnerVariantsInner
            //Assert.IsType<ContentV2CardsUploadPostRequestInnerVariantsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Brand'
        /// </summary>
        [Fact]
        public void BrandTest()
        {
            // TODO unit test for the property 'Brand'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'VendorCode'
        /// </summary>
        [Fact]
        public void VendorCodeTest()
        {
            // TODO unit test for the property 'VendorCode'
        }

        /// <summary>
        /// Test the property 'Dimensions'
        /// </summary>
        [Fact]
        public void DimensionsTest()
        {
            // TODO unit test for the property 'Dimensions'
        }

        /// <summary>
        /// Test the property 'Sizes'
        /// </summary>
        [Fact]
        public void SizesTest()
        {
            // TODO unit test for the property 'Sizes'
        }

        /// <summary>
        /// Test the property 'Characteristics'
        /// </summary>
        [Fact]
        public void CharacteristicsTest()
        {
            // TODO unit test for the property 'Characteristics'
        }
    }
}
