/*
 * Работа с товарами
 *
 * Работа с товарами включает в себя:   1. [Создание](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактирование](/openapi/work-with-products#tag/Kartochki-tovarov) карточек товаров: в том числе, получение [категорий, предметов и характеристик товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki) и загрузку [медиафайлов](/openapi/work-with-products#tag/Mediafajly).   2. Настройку [ярлыков](/openapi/work-with-products#tag/Yarlyki) для удобного поиска товаров.   3. Установку [цен и скидок](/openapi/work-with-products#tag/Ceny-i-skidki).   4. Управление [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца. 
 *
 * The version of the OpenAPI document: products
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing QuarantineGoods
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QuarantineGoodsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QuarantineGoods
        //private QuarantineGoods instance;

        public QuarantineGoodsTests()
        {
            // TODO uncomment below to create an instance of QuarantineGoods
            //instance = new QuarantineGoods();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QuarantineGoods
        /// </summary>
        [Fact]
        public void QuarantineGoodsInstanceTest()
        {
            // TODO uncomment below to test "IsType" QuarantineGoods
            //Assert.IsType<QuarantineGoods>(instance);
        }

        /// <summary>
        /// Test the property 'NmID'
        /// </summary>
        [Fact]
        public void NmIDTest()
        {
            // TODO unit test for the property 'NmID'
        }

        /// <summary>
        /// Test the property 'SizeID'
        /// </summary>
        [Fact]
        public void SizeIDTest()
        {
            // TODO unit test for the property 'SizeID'
        }

        /// <summary>
        /// Test the property 'TechSizeName'
        /// </summary>
        [Fact]
        public void TechSizeNameTest()
        {
            // TODO unit test for the property 'TechSizeName'
        }

        /// <summary>
        /// Test the property 'CurrencyIsoCode4217'
        /// </summary>
        [Fact]
        public void CurrencyIsoCode4217Test()
        {
            // TODO unit test for the property 'CurrencyIsoCode4217'
        }

        /// <summary>
        /// Test the property 'NewPrice'
        /// </summary>
        [Fact]
        public void NewPriceTest()
        {
            // TODO unit test for the property 'NewPrice'
        }

        /// <summary>
        /// Test the property 'OldPrice'
        /// </summary>
        [Fact]
        public void OldPriceTest()
        {
            // TODO unit test for the property 'OldPrice'
        }

        /// <summary>
        /// Test the property 'NewDiscount'
        /// </summary>
        [Fact]
        public void NewDiscountTest()
        {
            // TODO unit test for the property 'NewDiscount'
        }

        /// <summary>
        /// Test the property 'OldDiscount'
        /// </summary>
        [Fact]
        public void OldDiscountTest()
        {
            // TODO unit test for the property 'OldDiscount'
        }

        /// <summary>
        /// Test the property 'PriceDiff'
        /// </summary>
        [Fact]
        public void PriceDiffTest()
        {
            // TODO unit test for the property 'PriceDiff'
        }
    }
}
