/*
 * Работа с товарами
 *
 * Работа с товарами включает в себя:   1. [Создание](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактирование](/openapi/work-with-products#tag/Kartochki-tovarov) карточек товаров: в том числе, получение [категорий, предметов и характеристик товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki) и загрузку [медиафайлов](/openapi/work-with-products#tag/Mediafajly).   2. Настройку [ярлыков](/openapi/work-with-products#tag/Yarlyki) для удобного поиска товаров.   3. Установку [цен и скидок](/openapi/work-with-products#tag/Ceny-i-skidki).   4. Управление [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца. 
 *
 * The version of the OpenAPI document: products
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SupplierTaskMetadataBuffer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SupplierTaskMetadataBufferTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SupplierTaskMetadataBuffer
        //private SupplierTaskMetadataBuffer instance;

        public SupplierTaskMetadataBufferTests()
        {
            // TODO uncomment below to create an instance of SupplierTaskMetadataBuffer
            //instance = new SupplierTaskMetadataBuffer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SupplierTaskMetadataBuffer
        /// </summary>
        [Fact]
        public void SupplierTaskMetadataBufferInstanceTest()
        {
            // TODO uncomment below to test "IsType" SupplierTaskMetadataBuffer
            //Assert.IsType<SupplierTaskMetadataBuffer>(instance);
        }

        /// <summary>
        /// Test the property 'UploadID'
        /// </summary>
        [Fact]
        public void UploadIDTest()
        {
            // TODO unit test for the property 'UploadID'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'UploadDate'
        /// </summary>
        [Fact]
        public void UploadDateTest()
        {
            // TODO unit test for the property 'UploadDate'
        }

        /// <summary>
        /// Test the property 'ActivationDate'
        /// </summary>
        [Fact]
        public void ActivationDateTest()
        {
            // TODO unit test for the property 'ActivationDate'
        }

        /// <summary>
        /// Test the property 'OverAllGoodsNumber'
        /// </summary>
        [Fact]
        public void OverAllGoodsNumberTest()
        {
            // TODO unit test for the property 'OverAllGoodsNumber'
        }

        /// <summary>
        /// Test the property 'SuccessGoodsNumber'
        /// </summary>
        [Fact]
        public void SuccessGoodsNumberTest()
        {
            // TODO unit test for the property 'SuccessGoodsNumber'
        }
    }
}
